<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
// Lucent Innovation Sarvesh Patel
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */

$query = '';
if(isset($_GET['q']) && $_GET['q']!=''){
     $query = $_GET['q'];
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Request\Http');
?>
<style>
	.filter-options .filter-options-title{
		border: 1px solid #000;
    	padding: 10px;
    	margin: 0 0 0px;
	}
	.filter-options .filter-options-content{
		border-left: 1px solid #000;
		border-right: 1px solid #000;
	    padding-left: 10px;
	    border-bottom: 0;
	    margin-bottom: -3px;
	    padding: 10px;
	}
	dl dd:last-child {
		border-bottom: 1px solid #000 !important;
	}
	.page-title-wrapper{
		    text-align: center;
	}
	.cprice{
		font-size: 22px;
   		line-height: 40px;
   		color: #888;
	}
	.purl,a.purl:visited{
		height: 31px;
	    float: left;
	    margin: 10px 0px;
	    color: #888;
	}
	.filter-options-content li div span{
		z-index: -1;
		position: relative;
	}
	.filter-options-content li div{
		z-index: 100;
		position: relative;
	}
	.seleoption{
		float: left;
	    width: auto;
	    display: block;
	    min-width: 20px;
	    background: #ccc;
	    margin: 3px;
	    text-align: center;
	    border-radius: 3px;
	    font-size: 16px;
	    padding: 5px 10px;
	}
	.pager{
		color: #999;
	    padding: 10px;
	    font-size: 20px;
	    margin: 10px;
	    border-radius: 16px;
	    background: #ddd;
	    text-decoration: none;
	}
	.pager:hover{
	    text-decoration: none;
	}
	.pagenumber_static{
		color:#000;
	}
	.clicked{
		color:#ff0;
	}
	.swatch-option-selected {
	    border: 1px solid #f00;
	    cursor: pointer;
	    float: left;
	    height: 20px;
	    margin: 0 10px 5px 0;
	    max-width: 100%;
	    min-width: 30px;
	    overflow: hidden;
	    padding: 1px 2px;
	    position: relative;
	    text-align: center;
	    text-overflow: ellipsis;
	}
	.selectedprice{
		color:#f00;
	}

</style>





<script type="text/javascript">
    //<![CDATA[
 require([
    'jquery',
    'Magento_Ui/js/modal/alert'
    ], function($, alert) {
    	//$('#layer-product-list').html('');
		<?php
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
		if(isset($category)){
		    $category_id = $category->getId();
		}else{
		    $category_id = '';
		}

	    ?>
	    $('.swatch-attribute .swatch-option-link-layered').attr("href","javascript:;");


	   // $('#layer-product-list').html('<center style="font-size:50px;">Loding.....</center>');    	
	   filterProductbyattribute(option_id='',category_id='<?php echo $category_id; ?>',attribute_code='',label='',action='',limit='9',page='1',query='<?php echo $query; ?>',filterpage='<?php echo $request->getRouteName();?>');

	   //for add selection filter
       $('.filter-options-content li div').on('click', function(event){
            var option_id= $(event.target).attr('data'),
                attribute_code= $(event.target).attr('code'),
                label= $(event.target).attr('value'),
                category_id= $(event.target).attr('category-id');
                //var ids = option_id+' '+category_id; 
                //alert({ content:attribute_code});
                if(attribute_code=='price'){
            	$(event.target).addClass( "selectedprice" );
            	$('.price_class').removeClass( "selectedprice" );
                }else{
            	$(event.target).addClass( "selectedprice" );
                }
 	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       }),
      
       // remove selection filter	
       $('html').on('click','.seleoption', function(event){
       			
                var option_id= $(event.target).attr('option-id'),
                attribute_code= $(event.target).attr('data'),
                label= $(event.target).attr('option-id'),
                category_id= $(event.target).attr('category-id');
                $('.'+attribute_code+'_'+label).removeClass('selectedprice');
               

				var action= 'delete';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       }),
       
       //for pagination
       $('html').on('click','.pagenumber', function(event){
       			
                var page= $(event.target).attr('data'),
                limit= $(event.target).attr('limit');
				var action= 'pagination';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       })

       


	   function filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage){
		    $('#layer-product-list').html('<center style="font-size:50px;">Loding.....</center>');    	

	        var htmlData = '';
            $.post('<?php  echo $block->getUrl('hello/index/display'); ?>',{ id: option_id,cid: category_id,attribute_code: attribute_code,label: label,action: action,limit: limit,page: page,query: query,filterpage: filterpage},function(data){

							<?php
							if(!isset($_GET['q'])){
								$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); 		
								$category_name = $category->getName();
							?>	            		
			                    htmlData += '<center><h3><?php echo $category_name; ?>'; 
			                    htmlData += '</h3></center>'; 
			                <?php } ?>
            			    //alert({content:data.catalogsearch.values.category});
		                    htmlData += '<div class="row">'; 

		                    if(data.values.category!=''){
		                    	/*
		                    	$('.filter-options-content li div').attr('category-id',data.values.category);
			                    htmlData += '<a class="seleoption" data="category" option-id="'+data.values.category+'" value="'+data.values.category+'" category-id="<?php echo $category_id; ?>">'+data.values.categoryLabel+'</a>';  
			    			    $('.category_'+data.values.category).addClass('selectedprice');
			    			    */
		                    }	

			                var  pricefilter = '';
			                 <?php 
			               $attribute_array = array();
		$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
		$coll = $objectManager->create(\Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection::class);
		$coll->addIsFilterableFilter();
		$layeredNavAttributes = $coll->load()->getItems();
		$total_attributes =  sizeof($layeredNavAttributes);
		if($total_attributes > 0 ){
			foreach ($layeredNavAttributes AS $attr) {
				$attribute_data = $attr->getData();
				//array_push($attribute_array, $attribute_data['attribute_code']);
				$attribute_array[] = $attribute_data['attribute_code'];
			}
		}
							for($aa=0;$aa<sizeof($attribute_array);$aa++){
								$attribute_title = $attribute_array[$aa];
								if($attribute_title=='price'){

								?>
								
			                if(data.values.price!=''){   
			                    var pricedata  = data.values.price;
			                    var priceresult = pricedata.split('-');
			                    //alert({ content:priceresult[1]});
			                    if(priceresult[0] == ''){
			                    	pricefilter += 'less then '+priceresult[1];
			                    }else if (priceresult[1]== ''){
			                    	pricefilter += 'greater then '+priceresult[0];
			                    }else{
			                    	pricefilter += 'from '+priceresult[0]+' to '+priceresult[1];
			                    }
			                    htmlData += '<a  s class="seleoption" data="price" option-id="'+data.values.price+'" value="'+data.values.price+'" category-id="<?php echo $category_id; ?>">'+pricefilter+'</a>';  
			                 }
								<?php
								
								}else {
								?>
			            		var all_data  = data.values.attribute.<?php echo $attribute_title; ?>;
			            		var all_data_label  = data.values.attribute.<?php echo $attribute_title; ?>Label;
			            		//alert({content:'<?php echo $attribute_title; ?>'})
			            		if(all_data!=''){
					                if(all_data.length > 0 ){
					                    for(var a=0;a<all_data.length;a++){
											  $('.size_'+all_data[a]).addClass('selectedprice');
					                          htmlData += '<a class="seleoption" category-id="<?php echo $category_id; ?>" data="<?php echo $attribute_title; ?>" option-id="'+all_data[a]+'">'+all_data_label[a]+'</a>';  
					                    }
					                }
			            		}
								<?php 	
								}
							}
							?>

		            		
		                    htmlData += '</div><br/><br/>'; 

            		
		            <?php 
				        $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
				        $currencyCode = $currencysymbol->getStore()->getCurrentCurrencyCode();
				        $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
				        $currencySymbol = $currency->getCurrencySymbol();
					?>       	
                    htmlData += '<div class="row">'; 
	                if(data.products.length > 0 ){

	                    for(var i=0;i<data.products.length;i++){
	                          htmlData += '<div class="col-4" style="margin-bottom:20px;">';  
	                          htmlData += '<div style="width:100%;"><a href="'+data.products[i].url+'"><img style="height:300px;width:100%; display:block;" src="'+data.products[i].image+'"></a></div>';  
	                          htmlData += '<div class="row"><div class="col-12"><a class="purl" href="'+data.products[i].url+'">'+data.products[i].name+'</a></div></div>';  
	                          htmlData += '<div class="row"><div class="col-6"><div class="cprice"> <?php echo $currencySymbol;?> '+data.products[i].price+'</div></div>';  
	                          htmlData += '<div class="col-6" style="text-align:right;">'+data.products[i].addtocart+'</div>';  
	                          htmlData += '</div></div>';  
	                    }
	                }else{
	                    htmlData += '<div class="col-12">No Product Found!</div>'; 
	                }

	                htmlData += '<div class="col-12">'+data.pagination+'</div>'; 

                    htmlData += '</div>'; 

			    	$('.price_'+data.values.price).addClass('selectedprice');
                   

                    $('#layer-product-list').html(htmlData);
                },'json');
	   }
   }



 );
//]]>
</script>
<div class="block-content filter-content">
	<dl class="filter-options"  id="accordion" data-mage-init='{
        "accordion":{
            "active": [0],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
<dt data-role="collapsible" role="tab" aria-level="3" class="filter-options-title active" data-collapsible="true" aria-selected="false" aria-expanded="true" tabindex="0">Price</dt>   
<dd data-role="content" class="filter-options-content" role="tabpanel" aria-hidden="false">
<ol class="items">
	<li class="item">
	<div href="javascript:;" class="price_class  price_-100" value="-100" data="-100" category-id="<?php echo $category_id; ?>" code="price">
		<span class="price">$0.00</span> - <span class="price">$99.99</span>
	</div>
	</li>
	<li class="item">
	<div href="javascript:;" class="price_class  price_100-200" value="100-200" data="100-200" category-id="<?php echo $category_id; ?>" code="price">
		<span class="price">$100.00</span> - <span class="price">$199.99</span>
	</div>
	</li>
	<li class="item">
	<div href="javascript:;" class="price_class  price_200-300" value="200-300" data="200-300" category-id="<?php echo $category_id; ?>" code="price">
		<span class="price">$200.00</span> - <span class="price">$299.99</span>
	</div>
	</li>
	<li class="item">
	<div href="javascript:;" class="price_class  price_300-" value="300-" data="300-" category-id="<?php echo $category_id; ?>" code="price">
		<span class="price">$300.00</span> and above
	</div>
	</li>
</ol>


</dd>
<?php
$coll = $objectManager->create(\Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection::class);
$coll->addIsFilterableFilter();
$layeredNavAttributes = $coll->load()->getItems();
$total_attributes =  sizeof($layeredNavAttributes);
foreach ($layeredNavAttributes AS $attr) {
	$attribute_data = $attr->getData();
	$attribute_id = $attr->getId();
	$attribute_code = $attribute_data['attribute_code'];
	//echo $attribute_data['attribute_code'].'='.$attribute_id;
	//echo "<br>";
    $attr->setStoreId(0);

    $options = $attr->getSource()->getAllOptions();
    if(sizeof($options) > 1){
	echo "<dt data-role='collapsible' class='filter-options-title'>".$attribute_code."</dt>";
	echo "<dd data-role='content' class='filter-options-content'><ol class='items'>";
	    $i=0;
	    foreach ($options AS $option) {$i++;
	      $label =  $option['label'];
	      $value =  $option['value'];
	      echo "<li class='item'><div ".$i." class='".$attribute_data['attribute_code']."_class ".$attribute_data['attribute_code']."_".$value." '  value='".$label."' data='".$value."' category-id='".$category_id."' code='".$attribute_code."'>".$option['label']."</div></li>";
	      
	    }
	echo "</li></dd>";
	}
}
?>
	</dl>
</div>
